name: "CI"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Policies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install Custodian
        run: |
          pip install c7n_left
      - name: Pull Modules
        run: |
          terraform -chdir=root-module get
      - name: Check Terraform AWS
        run: |
          c7n-left run --policy-dir policies -d root-module
      - name: Check Terraform GCP
        run: |
          c7n-left run --policy-dir policies-gcp -d root-module-gcp

